### ISSUE TITLE
add server.js alias to support require('react-dom/server')

### ISSUE THREAD

**Issue by matthewmueller** [preact-compat/react-dom#1]
Cool project! Next.js looks for `require('react-dom/server)` directly, so it'd be good to just include that file in here.

**Comment by notpushkin** [comment]
Nice catch, thank you! I can fix it tomorrow or maybe would you like to send a pull request for that?

**Comment by notpushkin** [comment]
@matthewmueller Should be working now! Sorry for the delay.

**Comment by matthewmueller** [comment]
Thanks!
