### ISSUE TITLE
Publish branch 1.x to npm

### ISSUE THREAD

**Issue by soerenbf** [preact-compat/react-dom#3]
Hi there.

Made a PR yesterday #2 with some changes, which were already in another branch in this repo. Shouldn't the branch supporting the most recent version of preact be published to npm if it's ready?

Same for **preact-compat/react.**

**Comment by notpushkin** [comment]
@soerenbf We don't publish to npm at all. Let me explain :)

When you run `npm install preact-compat/react-dom`, it is a shorthand for `npm install https://github.com/preact-compat/react-dom.git`, which installs a package located in this repo. [We use `react-dom`][1] as the package name so it gets installed into `node_modules/react-dom` and can be imported with e. g. `import { render } from "react-dom"`.

This wouldn't work with npm: we would need to publish the package as `react-dom`, which of course isn't possible, as the original React-DOM package is there. The same goes for `react`. Hope that clears things up a bit!

[1]: https://github.com/preact-compat/react-dom/blob/master/package.json#L2

**Comment by soerenbf** [comment]
@notpushkin Oh, it certainly does! Never heard of doing it like that before. Sorry for the confusion.

Out of sheer curiosity (and if you have time to explain of course), how would one set up that shorthand functionality?

**Comment by notpushkin** [comment]
@soerenbf Yeah, it's actually more of a hack, that's why it isn't in the [docs][1] I guess.

> Out of sheer curiosity (and if you have time to explain of course), how would one set up that shorthand functionality?

Sorry, didn't get your question. Do you want to setup a replacement for some other library? (And if you're talking about `npm install user/repo`, this works out of the box for both npm and Yarn :)

[1]: https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact

**Comment by soerenbf** [comment]
> 
> 
> @soerenbf Yeah, it's actually more of a hack, that's why it isn't in the [docs](https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact) I guess.
> 
> > Out of sheer curiosity (and if you have time to explain of course), how would one set up that shorthand functionality?
> 
> Sorry, didn't get your question. Do you want to setup a replacement for some other library? (And if you're talking about `npm install user/repo`, this works out of the box for both npm and Yarn :)

Oh ok, the reason i got into this is because I'm taking the initial steps in a nextJS project, and aliasing in webpack didn't work as well as this "hack", which is why I wanted to update it. The question was more related to installing through github by user/repo (and not url), which I didn't know was possible, but you explained that part so thanks for that ;)
